%include "io.inc"

section .text
global CMAIN
CMAIN:
    mov ebp, esp; for correct debugging
    mov ah, 0    ; LIMPO OS 8bits MAIS SIGNIFICATIVOS DE AX
    mov al, '7'  ; MOVO O CARACTERE '7' PARA OS 8bits MENOS SIGNIFICATIVOS DE AX, DE ACORDO COM A TABELA ASCII 37 EM HEXADECIMAL
    add al, '9'  ; SOMO O CARACTERE '9' AO CARACTERE '7', OU SEJA, 37h + 39h, SEGUNDO A TABELA
    aaa ; ESSA INSTRUÇÃO AJUSTA O RESULTADO BINÁRIO DE UMA INSTRUÇÃO ADD OU ADC. FAZ O RESULTADO CONSISTENTE COM A REPRESENTAÇÃO DECIMAL EM ASCII
    add al, '8' ; SOMANDO O CARACTERE '8', OU SEJA, 37h + 39h + 38h, DE ACORDO COM A TABELA
    aaa ; AJUSTANDO NOVAMENTE A SOMA
    or ax, 3030h ; É FEITA UMA SOMA PARA NÃO GERAR CARRY COM O 3030h QUE SERIA O 00, OU SEJA, O AX VAI MUDAR PARA A REPRESENTAÇÃO ASCII, 3234h NO CASO, JÁ QUE
    ; 9 + 7 + 8 = 24
    xor eax, eax
    ret